- src/Lazy.jl
https://github.com/JuliaLang/julia/commit/e419a5648108cc8894a223ed368c1dc641c23826 removed all `0.3` deprecations. `Range1` was one of them.
> Replace deprecated Range1 with UnitRange.

- src/macros.jl
- src/tail.jl
- test/runtests.jl
https://github.com/JuliaLang/julia/pull/12285 changed the precedence of ``=>`` which now requires a couple of extra ``(...)``. Also added some explicit imports to the test file since they seem to be shadowed by exports from ``Base``.
> Fix '=>' precedence and shadowed exports.

- README.md
- src/Lazy.jl
- src/liblazy.jl
Remove the underscores in the following functions, 
```
take_last
drop_last
take_nth
take_while
drop_while
partition_by
split_at
split_by
group_by
```
> remove the underscores to unify the function names

- src/Lazy.jl
The generic function `foreach` is entering Julia Base with version 0.5 (and earlier versions via Compat).  However this function is also defined in Lazy.  This PR addresses the resulting conflict by importing `foreach` from the appropriate source so that Lazy extends `foreach` rather than defining it *ab initio*.
**Caveat** The type signature is the Lazy version of `foreach` makes this extension clear-cut  and straightforward.  However, `Base.foreach` has a different meaning as a generic function to `Lazy.foreach`.  So it may be preferable to avoid the conflict by no longer exporting `foreach` rather than extending it (as was done for other conflicting identifiers for issue #27).
> Extend foreach when defined by Base or Compat.

- src/macros.jl
Now that the deprecated syntax `{ ... }` is gone, the JSON macro can no longer work. It was unexported, undocumented, and untested, so it is fairly safe to remove.
As [far](https://github.com/search?utf8=%E2%9C%93&q=%22import+Lazy%3A+%40json%22+language%3AJulia&type=Code&ref=searchresults) as I can [tell](https://github.com/search?utf8=%E2%9C%93&q=%22import+Lazy.%40json%22+language%3AJulia&type=Code&ref=searchresults), this macro is [not used anywhere](https://github.com/search?utf8=%E2%9C%93&q=%22Lazy.%40json%22+language%3AJulia&type=Code&ref=searchresults).
> Remove json macro (which can no longer work)

- REQUIRE
Use Julia 0.4 instead of 0.3. MacroTools (a dependency in the REQUIRE file) uses only v0.4 and above.
> Bump Lazy from 0.3 to 0.4

- src/Lazy.jl
- test/runtests.jl
e.g. https://github.com/JunoLab/CodeTools.jl/issues/10 by not creating methods that take no inputs
> fix StackOverflow from Listables

- src/liblazy.jl
fixes deprecation warnings on v0.6. see JuliaLang/julia#18839 for more
details.
> switch to using new Base.Iterators module on v0.6

- src/liblazy.jl
Fixes #57
The `Predicate` wrapper for functions was removed from Base yesterday. Since this package depends on it, the package is failing on nightly. This PR simply copies the definition that was in Base into this package. It would be great if you could tag a release after this is merged so that the packages that depend on this won't also fail.
> Work around removal of Base.Predicate

- src/liblazy.jl
- test/runtests.jl
Note that these annotations used to be `Base.Predicate`, but they were removed when `Predicate` was removed from Base. Their removal is causing ambiguity warnings. This PR adds an annotation of `Union{Function, DataType}`, which should fix things.
cc @tkelman, @MikeInnes
> Fix ambiguities in any/all

- src/macros.jl
The `@init` macro doesn't work as-is on 0.7 master because the scoping/escaping rules changed (I *think* due to https://github.com/JuliaLang/julia/pull/22985, see also https://github.com/JuliaLang/julia/issues/23221). Also, `isdefined` is deprecated. This fixes all of these things in the best (only?) way I could thing of that works on both 0.6 and 0.7 with no depwarns.
> fix `@init` macro in light of new macro scoping rules in 0.7

- src/Lazy.jl
- test/runtests.jl
The call `colon(list(1), list(list(2)))` is ambiguous between `colon(x, xs::Lazy.List)` from `Lazy` and `colon(x::T, y::T) where T` from `Base`.
This is fixed by adding a special case method `colon(x::Lazy.List, xs::Lazy.List)` that is otherwise identical to `colon(x, xs::Lazy.List)`.
> fix: colon specialized for consing a list in front of a list

- README.md
- src/collections.jl
- src/liblazy.jl
I find this ``takeuntil`` function is somewhat useful.
Although in Clojure, this function is not included yet. 
https://dev.clojure.org/jira/browse/CLJ-1451
> add ``takeuntil`` function

- src/liblazy.jl
- test/runtests.jl
`reductions(f, v, xs)` should return the final reduction value as well as all intermediate steps. Instead, it returned the initial value `v` and the intermediate reductions, but not the final one.
For example, this is the old behavior:
```julia
julia> reductions(+, 0, list(1, 2, 3))
(0 1 3)
```
while this is the correct behavior, implemented in this PR:
```julia
julia> reductions(+, 0, list(1, 2, 3))
(1 3 6)
```
The question remains whether `reductions(f, xs)` should include `first(xs)` in the result or not.
Currently, it does not include the first element.
> reductions now includes the last reduction but not the initial value

- src/Lazy.jl
- src/macros.jl
- test/runtests.jl
- fixed issues with the threading macro `@>` when it's called on macros for Julia versions > 0.7 due to changes to macro parsing
- disabled `@_` macro for versions > 0.7
> fixed issues with threading macro for versions > 0.7

- src/macros.jl
- test/runtests.jl
See [this comment](https://github.com/MikeInnes/Lazy.jl/issues/98#issuecomment-427946449). In Julia 1.0 due to the extra argument to macros we need a different manipulation for macros than for functions.
> fix piping for function calls

- test/runtests.jl
Following up on a recent PR fixing some issues with using threading macros on functions (see [here](https://github.com/MikeInnes/Lazy.jl/pull/101)), I decided to clean up the tests for threading macros a little to make sure that glitches like the one in the PR mentioned above will be caught during testing in the future.
> Cleaned up tests for threading macros.

- src/tail.jl
There are two calls to `macroexpand` in this file, and one of them had apparently not yet been updated to use `@__MODULE__` as the first argument.
> Fix call to macroexpand in @bounce

- src/Lazy.jl
- test/runtests.jl
Even though ambiguities are not the problem they once were (prior to https://github.com/JuliaLang/julia/pull/16125), I still tend to try to avoid them. In several of my packages, I explicitly test that I've not inadvertently introduced an ambiguity. However, when I try running those tests in Juno's console, those packages fail due to an ambiguity in Lazy.jl.
This PR fixes the ambiguity. Experts should check whether this is the *right* fix :smile:.
> Eliminate an ambiguity in Colon

- src/macros.jl
- test/runtests.jl
Quick test:
```
using MacroTools
macro forward(ex, fs)
@capture(ex, T_.field_) || error("Syntax: @forward T.x f, g, h")
T = esc(T)
fs = isexpr(fs, :tuple) ? map(esc, fs.args) : [esc(fs)]
:($([:($f(x::$T, args...; kwargs...) = (Base.@_inline_meta; $f(x.$field, args...; kwargs...)))
for f in fs]...);
nothing)
end
struct Foo1 end
play(x::Foo1; y) = y
struct Foo2 
f::Foo1
end
@forward Foo2.f play
f1 = Foo1()
play(f1, y = 2)
f2 = Foo2(f1)
play(f2, y = 3)
```
> Support keyword arguments in forward macro

- .travis.yml
- src/liblazy.jl
- test/runtests.jl
Long running computation is better than `StackOverFlow` ?
(well, currently stackoverflow in this `length` results in a crash, somehow)
> try to avoid stackoverflow on `length`
